### ISSUE TITLE
Original test data and "Soil_Moisture_Retrieval_Data" and NetCDF: Bad chunk sizes

### ISSUE THREAD

**Issue by ngasset** [TUW-GEO/smap_io#9]
## Trying to run test_reshuffle I get the following error:

OSError: Unable to create file (unable to open file: name = '/fs/cetus/fs2/mrb/armn/armngan/tmp/try_pytesmo/test_data/smap_io/tests/test_data/spl3smp/2015.04.01/SMAP_L3_SM_P_20150401_R13080_001.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

 
## Then trying to play with SMAP L3 data I downloaded from n5eil01u.ecs.nsidc.org I get the following error:

  File "/data/ords/armn/armngan/miniconda2/envs/smap_io-environment/lib/python3.5/site-packages/smap_io/interface.py", line 76, in read
    latitude = ds['Soil_Moisture_Retrieval_Data']['latitude'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/data/ords/armn/armngan/miniconda2/envs/smap_io-environment/lib/python3.5/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Soil_Moisture_Retrieval_Data' doesn't exist)"

 
## Finally, adapting to "Soil_Moisture_Retrieval_Data_AM" in interface.py (as it appears to be the new name), i get the following error:

(smap_io-environment) armngan@arxt17:~/cetus/tmp/try_pytesmo/test_data/smap_io/tests$ python test_reshuffle.py 
/data/ords/armn/armngan/miniconda2/envs/smap_io-environment/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Converting data from 2016-04-01T00:00:00 to 2016-04-02T00:00:00 into folder /tmp/armngan/17803/tmp_qdmkv6m.
Traceback (most recent call last):
  File "test_reshuffle.py", line 59, in <module>
    test_reshuffle()
  File "test_reshuffle.py", line 47, in test_reshuffle
    reshuffle.main(args)
  File "/data/ords/armn/armngan/miniconda2/envs/smap_io-environment/lib/python3.5/site-packages/smap_io/reshuffle.py", line 137, in main
    imgbuffer=args.imgbuffer)
  File "/data/ords/armn/armngan/miniconda2/envs/smap_io-environment/lib/python3.5/site-packages/smap_io/reshuffle.py", line 85, in reshuffle
    reshuffler.calc()
  File "/data/ords/armn/armngan/miniconda2/envs/smap_io-environment/lib/python3.5/site-packages/repurpose/img2ts.py", line 300, in calc
    attributes=self.ts_attributes)
  File "/data/ords/armn/armngan/miniconda2/envs/smap_io-environment/lib/python3.5/site-packages/pynetcf/time_series.py", line 802, in write_ts_all_loc
    dtype=data[key].dtype, chunksizes=chunksizes)
  File "/data/ords/armn/armngan/miniconda2/envs/smap_io-environment/lib/python3.5/site-packages/pynetcf/base.py", line 207, in write_var
    chunksizes=chunksizes, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2291, in netCDF4._netCDF4.Dataset.createVariable (netCDF4/_netCDF4.c:18426)
  File "netCDF4/_netCDF4.pyx", line 3297, in netCDF4._netCDF4.Variable.__init__ (netCDF4/_netCDF4.c:31434)
RuntimeError: NetCDF: Bad chunk sizes.

## 
Am I missing something ??

**Comment by ngasset** [comment]
Ok managed to make it work. It is exactly netCDF4==1.2.2 that is needed while following the recipe from the README effectively installed version 1.2.8.

**Comment by cpaulik** [comment]
Sorry for the late reply. 

I think the NetCDF issue is the following: https://github.com/Unidata/netcdf4-python/issues/566 So the Python version should not be as important as the version of the C bindings.

The Variable names seem to have changed. Unfortunately we did not notice since we do not work with SMAP data very often.

**Comment by wpreimes** [comment]
Just for the record, the netcdf4 issue has been resolved. The latest version of netcdf4 will not raise this error anymore under any python version, therefor I close this issue.
